# Generated by Django 4.0.6 on 2024-05-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.IntegerField()),
                ('user_prompt', models.TextField()),
                ('response', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
