# Generated by Django 4.0.6 on 2024-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='user_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
