# Generated by Django 4.0.6 on 2025-03-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0002_conversations_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='actions_taken',
            field=models.TextField(default='no action recorded'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversations',
            name='response_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
